food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.index, name='index'),
    path('item/', views.item, name='item'), 
    path('<int:item_id>/', views.detail, name='detail'),
    path('add', views.create_item, name='create_item'),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name='delete_item')
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from users import views as user_views
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    # LoginView and LogoutView are inbuilt class based views 
]

food/models.py
from django.db import models

class Item(models.Model):

    def __str__(self):
        return self.item_name

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=1000, default="https://i.pinimg.com/originals/b6/9d/53/b69d53168ccb8e5daab6d5d460b773d8.jpg")
 

users/models.py
from django.db import models

# Create your models here.

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# RegisterForm class is inherting from class UserCreationForm
class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    # Meta class holds the information regarding RegisterForm class
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm

def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)
    # return HttpResponse(template.render(context, request))

def item(request):
    return HttpResponse('<h1>This is a item, hi !</h1>')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context ={
        'item':item,
    }
    return render(request, 'food/detail.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {  'form': form})

def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    context = {
        'form': form,
        'item': item,
    }
    return render(request, 'food/item-form.html', context)

def delete_item(request, id):
    item = Item.objects.get(id=id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item': item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username} your are Logged In !')
            return redirect('login')
    else:
        form = RegisterForm()

    return render(request, 'users/register.html', {'form':form})

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Food App</a>
        
        <div class="navbar">
            <a href="{% url 'food:create_item' %}" class="navbar-item nav-link" >Add Item</a>
            <a href="#" class="navbar-item nav-link">Delete Item</a>
            <a href="#"class="navbar-item nav-link">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
           <img height="300px" class="card" src="{{ item.item_image }}"> 
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>${{ item.item_price }}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
</head>
    <body>
        {% block body %}
            {% for item in item_list %}
                <div class="row">
                    <div class="col-md-3 offset-md-2">
                        <img class="card" height="150px" src="{{ item.item_image }}" alt="Food Image">
                    </div>
                    <div class="col-md-4">
                        <h2>{{ item.item_name }}</h2>
                        <h3>{{ item.item_desc }}</h3>
                        <h4>${{ item.item_price }}</h4>
                    </div>
                    <div class="col-md-2">
                        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
                    </div>
                </div>
            {% endfor %}
            {% endblock %}
                This is the old code     
            <ul>
                <li>
                    <a href="#">
                        {{ item.id }} -- {{ item.item_name }}   
                    </a>


                </li>
            </ul>
           


    </body>
</html>

food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }} ?</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
 
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

users/templates/users/logout.html
<h1>You have been Logged Out</h1>

users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Signup</button>
</form>